### ISSUE TITLE
bunx cextup fails

### ISSUE THREAD

**Issue by advait** [trvswgnr/cextup#6]
```
❯ bunx -v cextup
Extension name: asdf
node:internal/readline/emitKeypressEvents:74
            throw err;
            ^

Error: ENOENT: no such file or directory, copyfile '/tmp/bunx-1000-cextup@latest/node_modules/cextup/.gitignore' -> 'asdf/.gitignore'
    at Object.copyFileSync (node:fs:3029:11)
    at copyFile (file:///tmp/bunx-1000-cextup@latest/node_modules/cextup/bin/cextup.js:107:8)
    at cb (file:///tmp/bunx-1000-cextup@latest/node_modules/cextup/bin/cextup.js:45:5)
    at [_onLine] [as _onLine] (node:internal/readline/interface:414:7)
    at [_line] [as _line] (node:internal/readline/interface:887:18)
    at [_ttyWrite] [as _ttyWrite] (node:internal/readline/interface:1265:22)
    at ReadStream.onkeypress (node:internal/readline/interface:264:20)
    at ReadStream.emit (node:events:518:28)
    at emitKeys (node:internal/readline/utils:371:14)
    at emitKeys.next (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/tmp/bunx-1000-cextup@latest/node_modules/cextup/.gitignore',
  dest: 'asdf/.gitignore'
}

Node.js v20.11.0
```

```
❯ node --version
v20.11.0
```

```
❯ bun --version
1.1.6
```

**Comment by plaxorizor** [comment]
got this too

**Comment by henno** [comment]
@trvswgnr Any idea why this happens?

**Comment by trvswgnr** [comment]
not sure but i will explore today. what os are you on?

**Comment by henno** [comment]
> not sure but i will explore today. what os are you on?

macOS 14.5, Node.js v22.12.0, bun 1.2.7

**Comment by trvswgnr** [comment]
@henno @plaxorizor @advait this has been resolved in the latest published version; let me know if you have any issues
